n1 = int(input('Digite um valor:'))
n2 = int(input('Digite um valor:'))
n3 = int(input('Digite o produto da raiz:'))
print('A soma de {} com {} fica = {}'.format(n1, n2, n1 + n2))
print('A divisao de {} com {} fica = {}'.format(n1, n2, n1 /n2))
print('A multiplicação de {} com {} fica = {}'.format(n1, n2, n1 * n2))
print('A subitração de {} com {} fica = {}'.format(n1, n2, n1 - n2))
print('A produto de {} elevado a {} fica = {}'.format(n1, n2, n1 ** n2))
print('A divisao inteira de {} com {} fica = {}'.format(n1, n2, n1 // n2))
print('A sobra da divisao de {} com {} fica = {}'.format(n1, n2, n1 % n2))
print('O antecessor de {} é {}'.format(n1, (n1-1)))
print('A Raiz quadrada de {} é {}'.format(n1, n1 ** (1/2)))
print('A Raiz {} de {} é {:.2f}'.format(n3, n1, n1 ** (1/n3)))
print('A media dos 3 valores é: {}'.format((n1 + n2 + n3)/3))