n = int(input('Digite um número para ver sua tabuada: '))

print('_________')
print('{} vezes 1 = {}'.format(n, n * 1))
print('{} vezes 2 = {}'.format(n, n * 2))
print('{} vezes 3 = {}'.format(n, n * 3))
print('{} vezes 4 = {}'.format(n, n * 4))
print('{} vezes 5 = {}'.format(n, n * 5))
print('{} vezes 6 = {}'.format(n, n * 6))
print('{} vezes 7 = {}'.format(n, n * 7))
print('{} vezes 8 = {}'.format(n, n * 8))
print('{} vezes 9 = {}'.format(n, n * 9))
print('{} vezes 10 = {}'.format(n, n * 10))
print('_________')
